# Generated by Django 5.1.7 on 2025-03-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_text_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Правильный текстовый ответ'),
        ),
    ]
