# Generated by Django 5.1.7 on 2025-03-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0002_question_correct_text_answer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('test', 'order')},
        ),
    ]
